name: app-ci-pipeline

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".github/workflows/**"
      - ".deploy/**"
      - "src/**"
  pull_request:
    branches:
      - main

jobs:
  infra-terraform-stage:
    name: stage infrastructure deployment
    env:
      TF_VAR_stripe_secret_key: ${{ secrets.STRIPE_SECRET_KEY }}
      TF_VAR_web_app_url: ${{ secrets.WEB_APP_URL }}
      TF_VAR_web_hook_secret: ${{ secrets.WEB_HOOK_SECRET }}
    environment: nomad-stage
    runs-on: ubuntu-latest
    needs: build-ami
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - name: run terraform init in services dir
        run: cd .deploy/terraform/stage/services/webserver-cluster && terraform init
      - name: deploy webserver cluster on aws
        run: cd .deploy/terraform/stage/services/webserver-cluster && terraform apply -auto-approve
